Repository b2ihealthcare/snow-owl, pull requests merged in 2019-03, with the labels that each got.

#308 SO-3412: Fix RF2 import validator for unpublished effective times
  snomed/com.b2international.snowowl.snomed.importer.rf2/src/com/b2international/snowowl/snomed/importer/rf2/validation/AbstractSnomedValidator.java
Labels: bug

#310 [api] fix snowowl.api.rest MANIFEST.MF
  core/com.b2international.snowowl.api.rest/META-INF/MANIFEST.MF
Labels: bug

#312 Release v6.13.0 bugfixes day 2
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/exceptions/ApiError.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/merge/Merge.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/issue/ValidationIssue.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptUpdateRequest.java
Labels: enhancement

#314 Release v6.13.0 bugfixes day 4
  releng/com.b2international.snowowl.server.update/assembly/common/scripts/snowowl_validate.sh
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/exporter/Rf2DescriptionExporter.java
Labels: bug

#315 [snomed.import] Fix UUID - effective time uniqueness validation in ...
  snomed/com.b2international.snowowl.snomed.importer.rf2/src/com/b2international/snowowl/snomed/importer/rf2/validation/SnomedRefSetValidator.java
Labels: bug

#317 [reasoner] Ignore property chain hierarchies collection if no type IDs..
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormGenerator.java
Labels: enhancement

#318 SDD-905: Classification changes related to equivalent concept merging
  core/com.b2international.snowowl.api.rest/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/events/util/Promise.java
  snomed/com.b2international.snowowl.snomed.api.rest/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.datastore/pom.xml
  snomed/com.b2international.snowowl.snomed.ecl.tests/pom.xml
  snomed/com.b2international.snowowl.snomed.ecl/pom.xml
  snomed/com.b2international.snowowl.snomed.reasoner/plugin.xml
  snomed/com.b2international.snowowl.snomed.reasoner/schema/equivalentConceptMerger.exsd
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/classification/ClassifyOperation.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/classification/ReasonerTaxonomyInferrer.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/equivalence/EquivalentConceptMerger.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/equivalence/IEquivalentConceptMerger.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/ontology/DelegateOntology.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationJobRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
  tests/com.b2international.snowowl.test.commons/pom.xml
  tests/com.b2international.snowowl.test.dependencies/pom.xml
Labels: enhancement

#320 SO-3491 Add validation rule to check allowed characteristic types
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/ruleSnomedCommon3.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/validation-rules-common.json
  snomed/com.b2international.snowowl.validation.snomed/src/tests/java/com/b2international/snowowl/validation/snomed/BaseGenericValidationRuleTest.java
  snomed/com.b2international.snowowl.validation.snomed/src/tests/java/com/b2international/snowowl/validation/snomed/GenericValidationRuleTest.java
Labels: feature

#328 SO-3489: Change mrcm validation severity to warning
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/validation-rules-common.json
Labels: enhancement

#329 SO-3508: Validation export API issues
  core/com.b2international.snowowl.api.rest/src/com/b2international/snowowl/api/rest/util/CsvMessageConverter.java
  core/com.b2international.snowowl.api.rest/src/com/b2international/snowowl/api/rest/validation/ValidationRestService.java
  releng/com.b2international.snowowl.server.update/assembly/common/scripts/snowowl_validate.sh
Labels: bug, enhancement

#331 Report only active relationships with inactive reference upon merge / rebase conflicts
  snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/branches/SnomedMergeConflictTest.java
  snomed/com.b2international.snowowl.snomed.datastore.server/src/com/b2international/snowowl/datastore/server/snomed/merge/rules/SnomedInvalidRelationshipMergeConflictRule.java
Labels: bug
