Repository b2ihealthcare/snow-owl, pull requests merged in 2019-06, with the labels that each got.

#355 SO-3294: Support word highlighting in validation issues
  core/com.b2international.snowowl.core/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/StylingDetail.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/ValidationIssueDetails.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/ValidateRequest.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/eval/GroovyScriptValidationRuleEvaluator.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/eval/ValidationRuleEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/validation/SnomedQueryValidationRuleEvaluator.java
Labels: feature

#359 Classification API improvements
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedClassificationRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedReasonerRestService.java
Labels: enhancement, feature

#360 OWLAP-178 OWL Expression ConceptId and GCI filters
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/ModelAttributeParameterExpanderExt.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedReferenceSetMemberRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/domain/SnomedOwlExpressionFilters.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/domain/SnomedReferenceSetMemberRestSearch.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRefSetMemberDocumentSerializationTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRefSetMemberIndexEntry.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRefSetMemberSearchRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRefSetMemberSearchRequestBuilder.java
Labels: feature

#361 Merge the two /validations/{validationId}/issues REST methods into one based on content type
  core/com.b2international.snowowl.api.rest/src/com/b2international/snowowl/api/rest/validation/ValidationRestService.java
Labels: bug, enhancement

#364 Query OWL expressions by type or destination
  snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/components/SnomedRefSetMemberApiTest.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedReferenceSetMemberRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/domain/SnomedOwlExpressionFilters.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRefSetMemberDocumentSerializationTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRefSetMemberIndexEntry.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRefSetMemberSearchRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRefSetMemberSearchRequestBuilder.java
Labels: feature
