Repository b2ihealthcare/snow-owl, pull requests merged in 2019-04, with the labels that each got.

#333 Issue/so 3514 dsv export fixes
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/dsv/MapTypeRefSetDSVExporter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/dsv/SnomedSimpleTypeRefSetDSVExporter.java
Labels: bug

#336 SO-1331: Fix disconnect command behavior
  core/com.b2international.snowowl.datastore.server/src/com/b2international/snowowl/datastore/server/CDORepositoryManager.java
  core/com.b2international.snowowl.datastore.server/src/com/b2international/snowowl/datastore/server/InternalApplicationSessionManager.java
  core/com.b2international.snowowl.datastore.server/src/com/b2international/snowowl/datastore/server/session/ApplicationSessionManager.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/cdo/CDOConnectionFactory.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/cdo/CDOConnectionManager.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/cdo/CDOContainer.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/cdo/ICDORepositoryManager.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/session/IApplicationSessionManager.java
  core/com.b2international.snowowl.server.console/src/com/b2international/snowowl/server/console/UserSessionCommandProvider.java
Labels: bug, enhancement

#338 OWLAP-51: Effectivetime restore updates
  snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/SnomedRestFixtures.java
  snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/components/SnomedConceptApiTest.java
  snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/components/SnomedDescriptionApiTest.java
  snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/components/SnomedRefSetMemberParameterizedTest.java
  snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/components/SnomedRelationshipApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/ComponentIdUniquenessValidator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/EffectiveTimeRestorer.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/SnomedEditingContext.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptUpdateRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedDescriptionUpdateRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRelationshipUpdateRequest.java
Labels: feature

#337 OWLAP-49: Automatically determine concept definition status
  snomed/com.b2international.snowowl.snomed.api.impl/src/com/b2international/snowowl/snomed/api/impl/domain/ConceptInputCreator.java
  snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/components/SnomedConceptApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedConcept.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptCreateRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptUpdateRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedOWLAxiomHelper.java
Labels: feature

#343 [snomed.taxonomy] Fix taxonomy building for concepts introduced as inactive
  snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/io/SnomedCT_Release_INT_20150131_concept_as_inactive.zip
  snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/io/SnomedImportApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/taxonomy/TaxonomyGraphUpdater.java
Labels: bug

#342 SO-3558: Update OWL bundles to support more recent reasoner versions
  core/com.b2international.snowowl.api.rest/src/com/b2international/snowowl/api/rest/codesystem/CodeSystemRestService.java
  dependencies/pom.xml
  pom.xml
  releng/target-platform/pom.xml
  snomed/com.b2international.snowowl.snomed.core.feature/feature.xml
  snomed/com.b2international.snowowl.snomed.reasoner/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/classification/ReasonerTaxonomyInferrer.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/ontology/DelegateOntology.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/ontology/DelegateOntologyFactory.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/ontology/DelegateOntologyStub.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationJobRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/OntologyExportRequest.java
Labels: enhancement

#345 Convert Xtend classes to java classes
  snomed/com.b2international.snowowl.snomed.datastore/.classpath
  snomed/com.b2international.snowowl.snomed.datastore/pom.xml
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRewriter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRewriter.xtend
  snomed/com.b2international.snowowl.snomed.datastore/xtend-gen/.gitignore
  snomed/com.b2international.snowowl.snomed.ecl/.classpath
  snomed/com.b2international.snowowl.snomed.ecl/src/com/b2international/snowowl/snomed/ecl/EclRuntimeModule.java
  snomed/com.b2international.snowowl.snomed.ecl/src/com/b2international/snowowl/snomed/ecl/EclStandaloneSetup.java
  snomed/com.b2international.snowowl.snomed.ecl/src/com/b2international/snowowl/snomed/ecl/generator/EclGenerator.java
  snomed/com.b2international.snowowl.snomed.ecl/src/com/b2international/snowowl/snomed/ecl/generator/EclGenerator.xtend
  snomed/com.b2international.snowowl.snomed.ecl/src/com/b2international/snowowl/snomed/ecl/scoping/EclScopeProvider.java
  snomed/com.b2international.snowowl.snomed.ecl/src/com/b2international/snowowl/snomed/ecl/validation/EclValidator.java
  snomed/com.b2international.snowowl.snomed.ecl/src/com/b2international/snowowl/snomed/ecl/validation/EclValidator.xtend
  snomed/com.b2international.snowowl.snomed.ecl/xtend-gen/.gitignore
  snomed/com.b2international.snowowl.snomed.ql/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.ql/pom.xml
  tests/com.b2international.snowowl.test.commons/.classpath
  tests/com.b2international.snowowl.test.commons/pom.xml
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/json/JsonExtensions.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/json/JsonExtensions.xtend
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/rest/RestExtensions.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/rest/RestExtensions.xtend
  tests/com.b2international.snowowl.test.commons/xtend-gen/.gitignore
  tests/com.b2international.snowowl.test.dependencies/.classpath
  tests/com.b2international.snowowl.test.dependencies/META-INF/MANIFEST.MF
  tests/com.b2international.snowowl.test.dependencies/pom.xml
  tests/com.b2international.snowowl.test.dependencies/src/org/databene/contiperf/junit/ContiPerfRuleExt.java
  tests/com.b2international.snowowl.test.dependencies/src/org/databene/contiperf/junit/ContiPerfRuleExt.xtend
  tests/com.b2international.snowowl.test.dependencies/xtend-gen/.gitignore
Labels: enhancement
