Repository b2ihealthcare/snow-owl, pull requests merged in 2019-05, with the labels that each got.

#349 SO-3595: Wrap sync BulkRequests with IdRequest upon execution
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRepositoryCommitRequestBuilder.java
Labels: bug

#351 SNOMED CT REST API improvements
  commons/com.b2international.commons.base/src/com/b2international/commons/http/AcceptHeader.java
  commons/com.b2international.commons.base/src/com/b2international/commons/http/ExtendedLocale.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/Branch.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/BaseComponent.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/merge/Merge.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchResourceRequest.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/request/SearchIndexResourceRequest.java
  core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/review/Review.java
  releng/com.b2international.snowowl.server.update/.launch/snow-owl-oss.launch
  snomed/com.b2international.snowowl.snomed.api.rest/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/AbstractRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/AbstractSnomedRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/ModelAttributeParameterExpanderExt.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedBranchMergingRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedBranchReviewRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedBranchingRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedClassificationRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedConceptHistoryRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedConceptRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedDescriptionRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedExportRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedIdentifierRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedImportRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedReferenceSetHistoryRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedReferenceSetMemberRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedReferenceSetRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedRelationshipRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/browser/SnomedBrowserRestService.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/config/SnomedApiConfig.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/config/api-description.mkd
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/domain/SnomedConceptRestSearch.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/domain/SnomedDescriptionRestSearch.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/domain/SnomedReferenceSetMemberRestSearch.java
  snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/domain/SnomedRelationshipRestSearch.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedComponent.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedConcept.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedCoreComponent.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedDescription.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedRelationship.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/refset/SnomedReferenceSet.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/refset/SnomedReferenceSetMember.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/SnomedQueryEvaluationRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedComponentDocument.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedConceptDocument.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedDocument.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/domain/ClassificationTask.java
Labels: bug, enhancement

#352 SO-3560: Increase query column length
  documentation/src/main/asciidoc/scripts/migration_query/snowowl_v6.16_AlterQueryColumn.sql
  snomed/com.b2international.snowowl.snomed.refset.model/model/snomedrefset.ecore
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/SnomedRefSetType.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedAnnotationRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedAssociationRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedAttributeValueRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedComplexMapRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedConcreteDataTypeRefSetImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedConcreteDataTypeRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedDescriptionTypeRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedLanguageRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedMRCMAttributeDomainRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedMRCMAttributeRangeRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedMRCMDomainRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedMRCMModuleScopeRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedMappingRefSetImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedModuleDependencyRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedOWLExpressionRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedQueryRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedRefSetFactoryImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedRefSetImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedRefSetPackageImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedRegularRefSetImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedSimpleMapRefSetMemberImpl.java
  snomed/com.b2international.snowowl.snomed.refset.model/src/com/b2international/snowowl/snomed/snomedrefset/impl/SnomedStructuralRefSetImpl.java
Labels: enhancement
