Repository b2ihealthcare/snow-owl, pull requests merged in 2020-06, with the labels that each got.

#581 Add support for optimizing concept query inclusion/exclusion
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemRequests.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/QueryExpression.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/QueryExpressionDiff.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/QueryExpressionDiffs.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/TerminologyRepositoryPlugin.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/QueryOptimizeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/QueryOptimizeRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/QueryOptimizer.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/SnomedPlugin.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/request/SnomedQueryOptimizer.java
Labels: feature

#584 SO-4100: Extra concept non-current member fix
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AbstractSnomedApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AllSnomedApiTests.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptInactivationApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ComponentInactivationChangeProcessor.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/SnomedRepositoryPreCommitHook.java
Labels: bug

#580 SO-4103: New rule: Active descriptions on inactive concepts should have a single inactivation indicator member
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule671.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/validation-rules-common.json
  snomed/com.b2international.snowowl.validation.snomed/src/test/java/com/b2international/snowowl/validation/snomed/GenericValidationRuleTest.java
Labels: feature

#590 Support `.` and `~` characters in branch names
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionBranchTest.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranch.java
Labels: feature

#591 Support CodeSystemEntry and CodeSystemVersionEntry in TransactionContext.delete(Object, boolean) method
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/RepositoryTransactionContext.java
Labels: enhancement

#592 Release v7.7.0 fixes/changes
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/CodeSystemResourceRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/RevisionIndexRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/uri/ComponentURI.java
Labels: enhancement

#593 Release v7.7.0 fixes/changes
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequest.java
Labels: enhancement

#596 [core] make TransactionContexts reusable for subsequent commits
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/attachments/Attachment.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/attachments/AttachmentRegistry.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/events/DelegatingRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BranchRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ExportRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/LockRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/RepositoryCommitRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/RevisionIndexRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/TransactionalRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptCreateRequest.java
Labels: enhancement

#598 Release v7.7.0 fixes/changes
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/Concept.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/uri/CodeSystemURI.java
Labels: enhancement
