Repository b2ihealthcare/snow-owl, pull requests merged in 2020-08, with the labels that each got.

#627 [validation] fix missing limit setting when collecting attributes...
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule110.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/test/java/com/b2international/snowowl/validation/snomed/GenericValidationRuleTest.java
Labels: bug

#629 Rebase commits now have their own unique timestamps
  commons/com.b2international.index/src/com/b2international/index/revision/BaseRevisionBranching.java
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ComponentInactivationChangeProcessor.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/SnomedRepositoryPreCommitHook.java
Labels: bug, enhancement

#634 SO-4202: fix merge performance issue when merging huge amount of changes into a branch
  commons/com.b2international.commons/src/com/b2international/commons/async/AsyncTask.java
  commons/com.b2international.commons/src/com/b2international/commons/exceptions/AlreadyExistsException.java
  commons/com.b2international.commons/src/com/b2international/commons/exceptions/ComponentStatusConflictException.java
  commons/com.b2international.commons/src/com/b2international/commons/status/SerializableStatus.java
  commons/com.b2international.index.tests/src/com/b2international/index/AggregationsTest.java
  commons/com.b2international.index/src/com/b2international/index/es/query/EsQueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/mapping/DocumentMapping.java
  commons/com.b2international.index/src/com/b2international/index/revision/DefaultRevisionIndex.java
  commons/com.b2international.index/src/com/b2international/index/revision/ObjectId.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranch.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionCompareDetail.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionIndex.java
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/util/ModelAttributeParameterExpanderExt.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/ComponentIdentifier.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/SnowOwl.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/authorization/BranchAccessControl.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/AbstractBranchChangeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystem.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/version/CodeSystemVersionCreateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/file/FileIdentityProvider.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/validation/ValidationRuleSchedulingRule.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/uri/CodeSystemURI.java
  core/com.b2international.snowowl.identity.ldap/src/com/b2international/snowowl/identity/ldap/LdapIdentityProvider.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/codesystems/FhirCodeSystem.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/BaseFhirResourceRestService.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirCodeSystemRestService.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirConceptMapRestService.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirValueSetRestService.java
  net4j/com.b2international.snowowl.eventbus/src/com/b2international/snowowl/eventbus/net4j/EventBusNet4jUtil.java
Labels: bug

#635 SO-4199: Snowowl command export NPE
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/console/BaseCommand.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/console/SnowOwlCommandProvider.java
Labels: bug

#638 Fix for task synchronization conflicts
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranchChangeSet.java
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/branches/SnomedMergeApiTest.java
Labels: bug

#637 SO-4219: Comparing large sets times out
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptMapCompareRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptMapSearchRequestEvaluator.java
Labels: bug

#643 Validation: improve performance of rule 671
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule671.groovy
Labels: enhancement

#641 Upgrade Elasticsearch to 7.9.0
  commons/com.b2international.index/.classpath
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/pom.xml
  docker/docker-compose.yml
Labels: dependencies, enhancement

#646 SO-4229 support change vs remove use case in branch compare
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionCompareTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionFixtures.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionCompare.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionCompareDetail.java
Labels: enhancement
