Repository b2ihealthcare/snow-owl, pull requests merged in 2020-05, with the labels that each got.

#555 Feature: support JSON MRCM export format
  snomed/com.b2international.snowowl.snomed.datastore.server/src/com/b2international/snowowl/snomed/core/mrcm/io/JsonMrcmExporter.java
  snomed/com.b2international.snowowl.snomed.datastore.server/src/com/b2international/snowowl/snomed/core/mrcm/io/MrcmCommandProvider.java
  snomed/com.b2international.snowowl.snomed.datastore.server/src/com/b2international/snowowl/snomed/core/mrcm/io/MrcmExporterImpl.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/constraint/SnomedConceptSetDefinition.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/constraint/SnomedPredicate.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/mrcm/io/MrcmExportFormat.java
Labels: feature

#556 Release v7.6.0 changes
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemApiTest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/TransactionalRequest.java
  core/com.b2international.snowowl.identity.ldap/src/com/b2international/snowowl/identity/ldap/LdapIdentityProvider.java
  core/com.b2international.snowowl.identity.ldap/src/com/b2international/snowowl/identity/ldap/LdapIdentityProviderConfig.java
  snomed/com.b2international.snowowl.snomed.common/src/com/b2international/snowowl/snomed/common/SnomedTerminologyComponentConstants.java
Labels: enhancement

#557 Release 7.6.0 fixes
  core/com.b2international.snowowl.identity.ldap/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.identity.ldap/src/com/b2international/snowowl/identity/ldap/LdapIdentityPlugin.java
  core/com.b2international.snowowl.identity.ldap/src/com/b2international/snowowl/identity/ldap/LdapIdentityProvider.java
  core/com.b2international.snowowl.identity.ldap/src/com/b2international/snowowl/identity/ldap/LdapIdentityProviderConfig.java
  docs/setup/security/ldap.md
  releng/com.b2international.snowowl.server.update/assembly/common/migration/6.16.0/snomedStore_6.16.0.sql
  releng/com.b2international.snowowl.server.update/assembly/common/migration/6.21.0/README.md
  releng/com.b2international.snowowl.server.update/assembly/common/migration/6.21.0/snomedStore_6.21.0.sql
Labels: enhancement

#547 Upgrade Eclipse/Equinox to 2020-03
  README.md
  cis/com.b2international.snowowl.snomed.cis.product/.launch/snow-owl-cis.launch
  commons/com.b2international.collections.api/META-INF/MANIFEST.MF
  commons/com.b2international.commons.base/.project
  commons/com.b2international.commons.base/META-INF/MANIFEST.MF
  commons/com.b2international.commons.base/src/com/b2international/commons/AlphaNumericComparator.java
  commons/com.b2international.commons.base/src/com/b2international/commons/StringUtils.java
  commons/com.b2international.commons.test/.launch/commons-tests.launch
  commons/com.b2international.index.tests/.launch/index-http-unit-tests.launch
  commons/com.b2international.index.tests/.launch/index-tcp-unit-tests.launch
  commons/com.b2international.index.tests/META-INF/MANIFEST.MF
  commons/com.b2international.index/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core.dependencies.feature/feature.xml
  core/com.b2international.snowowl.core.rest.tests/.launch/core-e2e-tests.launch
  core/com.b2international.snowowl.core.tests/.launch/core-unit-tests.launch
  core/com.b2international.snowowl.core.tests/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/events/util/Promise.java
  fhir/com.b2international.snowowl.fhir.rest.tests/.launch/fhir-api-tests.launch
  fhir/com.b2international.snowowl.fhir.rest.tests/.launch/fhir-unit-tests.launch
  fhir/com.b2international.snowowl.fhir.rest.tests/META-INF/MANIFEST.MF
  fhir/com.b2international.snowowl.fhir.rest/.launch/fhir-api-server.launch
  net4j/com.b2international.snowowl.eventbus.tests/.launch/eventbus-unit-tests.launch
  net4j/com.b2international.snowowl.eventbus/META-INF/MANIFEST.MF
  net4j/com.b2international.snowowl.rpc.test/.launch/rpc-unit-tests.launch
  net4j/com.b2international.snowowl.rpc/META-INF/MANIFEST.MF
  pom.xml
  releng/com.b2international.snowowl.server.update/.launch/snow-owl-oss.launch
  releng/target-platform/pom.xml
  releng/target-platform/target-platform.target
  snomed/com.b2international.snowowl.snomed.core.rest.tests/.launch/snomed-e2e-tests (cis).launch
  snomed/com.b2international.snowowl.snomed.core.rest.tests/.launch/snomed-e2e-tests.launch
  snomed/com.b2international.snowowl.snomed.core.rest.tests/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.datastore.tests/.launch/snomed-core-unit-tests.launch
  snomed/com.b2international.snowowl.snomed.datastore.tests/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.ecl.tests/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.ecl/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.etl.tests/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.ql.tests/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.reasoner.tests/.launch/snomed-reasoner-unit-tests.launch
  snomed/com.b2international.snowowl.snomed.reasoner.tests/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.scg.tests/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.scg/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.validation.snomed/.launch/validation-snomed-tests.launch
  snomed/com.b2international.snowowl.validation.snomed/META-INF/MANIFEST.MF
  tests/com.b2international.restassured-all/META-INF/MANIFEST.MF
  tests/com.b2international.snowowl.test.commons/META-INF/MANIFEST.MF
Labels: enhancement

#562 SO-4082: upgrade Elasticsearch to 7.7.0 and Lucene to 8.5.1
  commons/com.b2international.index/.classpath
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/pom.xml
  docker/docker-compose.yml
Labels: enhancement

#560 Improve iconId calculation to handle new semantic types
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ConceptChangeProcessor.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/SnomedRepositoryPreCommitHook.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/update/IconIdUpdater.java
  snomed/com.b2international.snowowl.snomed.icons/src/icons/clinical_drug.png
  snomed/com.b2international.snowowl.snomed.icons/src/icons/disorder.png
  snomed/com.b2international.snowowl.snomed.icons/src/icons/medicinal_product.png
  snomed/com.b2international.snowowl.snomed.icons/src/icons/medicinal_product_form.png
  snomed/com.b2international.snowowl.snomed.icons/src/icons/product.png
Labels: enhancement

#563 Export and Attachment API improvements
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/attachments/Attachment.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/attachments/AttachmentRegistry.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/console/BaseCommand.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ExportRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ExportRequestBuilder.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/Services.java
Labels: enhancement

#566 SO-4092: fix special search key pattern matching error
  core/com.b2international.snowowl.core.tests/src/com/b2international/snowowl/core/request/SearchResourceRequestTest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchResourceRequest.java
Labels: bug

#568 SO-4081: add shortcuts to ECL evaluator
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequestTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclShortcutTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/AllSnomedDatastoreTests.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequest.java
  snomed/com.b2international.snowowl.snomed.ecl/src/com/b2international/snowowl/snomed/ecl/Ecl.java
Labels: enhancement

#570 Configure default Elasticsearch disk thresholds
  commons/com.b2international.index/src/com/b2international/index/es/EsNode.java
Labels: enhancement

#571 SO-4095: support active filter in generic ConceptSearchRequest
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptSearchRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptSearchRequestEvaluator.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptSuggestionRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/request/SnomedConceptSearchRequestEvaluator.java
Labels: enhancement

#574 SO-4095: return suggestions with topTokens
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/Suggestions.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptSuggestionRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptSuggestionRequestBuilder.java
Labels: enhancement
