Repository b2ihealthcare/snow-owl, pull requests merged in 2020-09, with the labels that each got.

#651 Deprecate SNOMEDCT code system shortname and repositoryId constants
  snomed/com.b2international.snowowl.snomed.common/src/com/b2international/snowowl/snomed/common/SnomedTerminologyComponentConstants.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/SnomedDatastoreActivator.java
Labels: enhancement

#652 Potential duplicate revisions on child branch after merged changes from parent
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranchChangeSet.java
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedRestFixtures.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/branches/SnomedMergeApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/branches/SnomedMergeConflictTest.java
Labels: bug

#664 SO-4289: incorrect reuse of indicator member
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AllSnomedApiTests.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedComponentRestRequests.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedComponentInactivationApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedDescriptionApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/refset/SnomedReferenceSetMember.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ComponentInactivationChangeProcessor.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ExportRequest.java
Labels: bug

#665 SO-4265: Support switching between PT and FSN
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/tree/TreeBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/tree/TreeBuilderImpl.java
Labels: feature

#660 SO-4207: Support fetching concept maps by source and target ID
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/ConceptMapMapping.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptMapMappingSearchRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SetSearchRequestEvaluator.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/request/MemberSearchRequestSnomedTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptMapSearchRequestEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRefSetMemberSearchRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRefSetMemberSearchRequestBuilder.java
Labels: enhancement

#667 [lcs] Auxiliary support for configurable local code systems
  commons/com.b2international.commons/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/Branch.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemEntry.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemSearchRequestBuilder.java
Labels: feature

#669 Improve default text analysis settings
  commons/com.b2international.index/src/com/b2international/index/Analyzers.java
  commons/com.b2international.index/src/com/b2international/index/Normalizers.java
  commons/com.b2international.index/src/com/b2international/index/es/admin/EsIndexAdmin.java
  commons/com.b2international.index/src/com/b2international/index/es/admin/EsTextAnalysis.java
  commons/com.b2international.index/src/com/b2international/index/es/admin/analysis.json
  commons/com.b2international.index/src/com/b2international/index/es/query/EsQueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/query/Expressions.java
  commons/com.b2international.index/src/com/b2international/index/query/TextPredicate.java
Labels: enhancement

#679 ConceptMapMapping model improvements
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/ConceptMapMapping.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptMapMappingSearchRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SetSearchRequestEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/SnomedDisplayTermType.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptMapSearchRequestEvaluator.java
Labels: enhancement

#680 SO-4264: use JSON patch to apply property conflicts during merge
  commons/com.b2international.commons/.classpath
  commons/com.b2international.commons/META-INF/MANIFEST.MF
  commons/com.b2international.commons/pom.xml
  commons/com.b2international.index.tests/src/com/b2international/index/PartialDocumentLoadingTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/revision/NestedDocumentRevisionIndexTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionBranchMergeTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionFixtures.java
  commons/com.b2international.index/src/com/b2international/index/es/HitConverter.java
  commons/com.b2international.index/src/com/b2international/index/revision/Revision.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionCompareDetail.java
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/version/SnomedVersioningRequest.java
Labels: enhancement

#682 Upgrade Elasticsearch to 7.9.2
  commons/com.b2international.index/.classpath
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/pom.xml
  docker/docker-compose.yml
Labels: enhancement
