Repository b2ihealthcare/snow-owl, pull requests merged in 2020-04, with the labels that each got.

#530 Bump Elasticsearch to the latest 7.6.2 release
  commons/com.b2international.index/.classpath
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/build.properties
  commons/com.b2international.index/pom.xml
  commons/com.b2international.index/src/com/b2international/index/es/admin/analysis.json
Labels: enhancement

#532 SO-4007 Restore effectiveTime during RF2 Delta imports
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/ServiceProvider.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/jobs/RemoteJob.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/jobs/RemoteJobTracker.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/SnomedRepositoryPreCommitHook.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequest.java
Labels: enhancement

#533 Fix registration of additional TerminologyComponent types in registry
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/TerminologyRepositoryPlugin.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/terminology/TerminologyRegistry.java
Labels: bug

#534 Path expressions not working
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/version/VersioningRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/BranchContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/DelegatingBranchContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/RepositoryBranchContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/RepositoryContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/Locks.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/RepositoryTransactionContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/RevisionIndexReadRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/ValidateRequest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/branch/BranchCompareRequestTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/branch/SnomedBranchRequestTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/branches/SnomedMergeApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/EclExpression.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRefinementEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ExportRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/OntologyExportRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/snomed/TestBranchContext.java
Labels: bug

#527 SO-3965: Add lock context to non-SNOMEDCT import requests
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/LockRequest.java
Labels: enhancement

#540 Fix licensing issues reported by FOSSA
  core/com.b2international.snowowl.core.rest/snow-owl-api-docs/package-lock.json
  core/com.b2international.snowowl.core.rest/snow-owl-api-docs/package.json
  pom.xml
Labels: enhancement

#539 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: feature

#541 SO-4039 query expression labeler API
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequestTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedStatedEclEvaluationTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ql/SnomedQueryLabelerRequestTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/tree/TerminologyTreeTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/AllSnomedDatastoreTests.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/id/RandomSnomedIdentiferGenerator.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/change/BaseChangeProcessorTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/change/DescriptionChangeProcessorTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/change/PreferredDescriptionPreCommitHookTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/change/RelationshipChangeProcessorTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedConceptDocumentTermSortTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedConstraintDocumentSerializationTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedDescriptionIndexEntrySerializationTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRelationshipIndexEntrySerializationTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/validation/SnomedQueryValidationRuleEvaluatorTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/validation/SnomedValidationIssueDetailTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/SnomedQueryLabelerRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/SnomedQueryLabelerRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRequests.java
  snomed/com.b2international.snowowl.snomed.ecl/src/com/b2international/snowowl/snomed/ecl/converter/EclValueConverterService.java
  snomed/com.b2international.snowowl.snomed.ecl/src/com/b2international/snowowl/snomed/ecl/converter/TermStringConverter.java
  snomed/com.b2international.snowowl.snomed.etl.tests/src/com/b2international/snowowl/snomed/etl/tests/EtlParsingTest.xtend
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/snomed/RandomSnomedIdentiferGenerator.java
Labels: feature

#544 SO-3947: Make maximum file upload configurable
  commons/com.b2international.index/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core.rest/.classpath
  core/com.b2international.snowowl.core.rest/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core.rest/WEB-INF/web.xml
  core/com.b2international.snowowl.core.rest/pom.xml
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/ControllerExceptionMapper.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/SnowOwlApiConfig.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/rate/ApiConfiguration.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/rate/HttpConfig.java
Labels: dependencies, enhancement

#548 [docs] update security realm guide and configurations
  docs/setup/security/file.md
  docs/setup/security/index.md
  docs/setup/security/ldap.md
Labels: docs

#549 SO-4058: Support setting start/end effective times in RF2 export script
  releng/com.b2international.snowowl.server.update/assembly/common/scripts/snowowl_export.sh
Labels: enhancement

#550 RF2 Export issue
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ExportRequest.java
Labels: bug
