Repository b2ihealthcare/snow-owl, pull requests merged in 2021-05, with the labels that each got.

#801 SO-4797: Migrate validation rules to the common package
  snomed/com.b2international.snowowl.validation.snomed/.launch/validation-snomed-tests.launch
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/validation-rules-common.json
  snomed/com.b2international.snowowl.validation.snomed/src/test/java/com/b2international/snowowl/validation/snomed/GenericValidationRuleTest.java
Labels: enhancement, feature

#804 SO-4798: Migrate module restricted rules
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/validation/ValidationConfiguration.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/validation/SnomedQueryValidationRuleEvaluator.java
  snomed/com.b2international.snowowl.validation.snomed/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/Non-Acceptable_Semantic_Tags.txt
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule110.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule266.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule34.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule482.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule532a.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule532b.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule55.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule664.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule665.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule670.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule671.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule75.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule80.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint_type.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/validation-rules-common.json
  snomed/com.b2international.snowowl.validation.snomed/src/test/java/com/b2international/snowowl/validation/snomed/BaseGenericValidationRuleTest.java
  snomed/com.b2international.snowowl.validation.snomed/src/test/java/com/b2international/snowowl/validation/snomed/GenericValidationRuleTest.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/validation/BaseValidationTest.java
Labels: enhancement, feature

#807 fix(index): use segment diff to compute accurate base/head timestamps...
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionBranchMergeTest.java
  commons/com.b2international.index/src/com/b2international/index/revision/BaseRevisionBranching.java
Labels: bug

#802 SO-4800: RF2 import incorrect release flag
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedCT_Release_INT_20210502_concept_w_eff_time.zip
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedCT_Release_INT_20210502_concept_wo_eff_time.zip
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedImportApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/importer/Rf2TransactionContext.java
Labels: bug

#799 SO-4784: Disable version creation on branch
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedImportApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequestBuilder.java
Labels: enhancement

#803 SO-4776: Allow import to progress in spite of missing referenced components
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedCT_Release_INT_20150131_missing_component.zip
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedImportApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedRf2ImportRestService.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/config/SnomedCoreConfiguration.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/importer/Rf2AssociationRefSetContentType.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/importer/Rf2AttributeValueRefSetContentType.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/importer/Rf2EffectiveTimeSlice.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/validation/Rf2GlobalValidator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/validation/Rf2ValidationDefects.java
Labels: feature

#808 SO-4804: Support upgrading and synchronizing versioned content only
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemUpgradeRestInput.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemUpgradeRestService.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystem.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemCompleteUpgradeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/UpgradeInfo.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/version/CodeSystemVersionSearchRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/uri/DefaultResourceURIPathResolver.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedComponentEffectiveTimeRestoreTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionUpgradeTest.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/codesystem/CodeSystemRestRequests.java
Labels: enhancement
