Repository b2ihealthcare/snow-owl, pull requests merged in 2021-06, with the labels that each got.

#824 Update SnomedConcept.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedConcept.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/ontology/DelegateOntology.java
Labels: enhancement

#829 Groovy extension constant
  core/com.b2international.snowowl.core.tests/src/com/b2international/snowowl/core/scripts/GroovyScriptEngineTest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/console/ScriptsCommand.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/scripts/GroovyScriptEngine.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/eval/GroovyScriptValidationRuleEvaluator.java
Labels: enhancement

#827 Add case sensitivity flag to term filter
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/TermFilter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/TermFilterSupport.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedDescriptionApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/SnomedQueryEvaluationRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedDescriptionIndexEntry.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedDescriptionSearchRequest.java
Labels: enhancement

#834 Clean up FHIR launch config
  fhir/com.b2international.snowowl.fhir.rest/.launch/fhir-api-server.launch
Labels: dependencies

#836 Implement resource commit get request
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/resource/ResourceRestService.java
Labels: feature
