Repository b2ihealthcare/snow-owl, pull requests merged in 2021-02, with the labels that each got.

#752 SO-4642: Change module of inactivated content
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedDescriptionApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/SnomedPlugin.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ComponentInactivationChangeProcessor.java
Labels: enhancement

#757 SO-4635: support complete of code system upgrades
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/BranchInfo.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystem.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemCompleteUpgradeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemCompleteUpgradeRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemRequests.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystems.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/RepositoryTransactionContext.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionUpgradeTest.java
Labels: enhancement

#759 SO-4659: Map compare to consider active mappings only
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptMapCompareRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptMapMappingSearchRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SetSearchRequestEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptMapSearchRequestEvaluator.java
Labels: bug

#756 SO-4654: Partial promotion issue
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
Labels: bug

#765 Prevent unnecessary branch delete attempt in case of regular version create requests
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/version/CodeSystemVersionCreateRequest.java
Labels: enhancement

#767 SO-4683: Optionally carry over comments from mappings
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/ConceptMapMapping.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptMapCompareRequest.java
Labels: enhancement

#768 Minor API fixes/improvements
  commons/com.b2international.commons/src/com/b2international/commons/StringUtils.java
  commons/com.b2international.index.tests/.launch/index-http-unit-tests.launch
  commons/com.b2international.index.tests/.launch/index-tcp-unit-tests.launch
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionCompare.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/compare/BranchCompareRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/TransactionContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/RepositoryTransactionContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/TransactionalRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/importer/Rf2TransactionContext.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/AbstractCoreApiTest.java
Labels: bug, enhancement

#770 SO-4692: support rescoring of dismax query clauses on index level
  commons/com.b2international.index/src/com/b2international/index/mapping/DocumentMapping.java
  commons/com.b2international.index/src/com/b2international/index/query/Expressions.java
  commons/com.b2international.index/src/com/b2international/index/revision/Revision.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/commit/CommitInfoSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/issue/ValidationIssue.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/issue/ValidationIssueSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/whitelist/ValidationWhiteList.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/whitelist/ValidationWhiteListSearchRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedDescriptionIndexEntry.java
Labels: enhancement
