Repository b2ihealthcare/snow-owl, pull requests merged in 2021-01, with the labels that each got.

#731 SO-4136: Validate LDAP identity settings at server startup
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/AdminPartyIdentityProvider.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/IdentityPlugin.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/IdentityProvider.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/MultiIdentityProvider.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/file/FileIdentityProvider.java
  core/com.b2international.snowowl.identity.ldap/src/com/b2international/snowowl/identity/ldap/LdapIdentityPlugin.java
  core/com.b2international.snowowl.identity.ldap/src/com/b2international/snowowl/identity/ldap/LdapIdentityProvider.java
Labels: enhancement

#730 Add support method to SCT description domain.
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedDescription.java
Labels: enhancement

#733 SO-4590: support random Base64 UUID generation
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/id/IDs.java
Labels: enhancement

#735 SO-3964: upgrade effective time restore
  commons/com.b2international.commons/src/com/b2international/commons/exceptions/ApiException.java
  commons/com.b2international.commons/src/com/b2international/commons/exceptions/NotFoundException.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/AbstractRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemUpdateRestInput.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystem.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemCreateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemCreateRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemEntry.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemRequests.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/merge/MergeConflict.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/uri/CodeSystemURI.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AbstractSnomedApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AllSnomedApiTests.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/CodeSystemRestRequests.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedComponentRestRequests.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedRestFixtures.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedComponentEffectiveTimeRestoreTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ComponentEffectiveTimeRestoreChangeProcessor.java
Labels: feature

#734 SO-4582: support branchPrefix filter in CommitInfoSearchRequest
  commons/com.b2international.index/src/com/b2international/index/revision/Commit.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/commit/CommitInfoSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/commit/CommitInfoSearchRequestBuilder.java
Labels: enhancement

#739 SO-4227: migrate 6.x donation logic
  commons/com.b2international.commons/META-INF/MANIFEST.MF
  commons/com.b2international.commons/src/com/b2international/commons/exceptions/ApiException.java
  commons/com.b2international.commons/src/com/b2international/commons/json/Json.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranchChangeSet.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionConflictProcessor.java
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemVersionService.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeRequest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AbstractSnomedApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AllSnomedApiTests.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/CodeSystemVersionRestRequests.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedRestFixtures.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/classification/SnomedClassificationApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptInactivationApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedDescriptionApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedModuleDependencyRefsetTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRefSetBulkApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRefSetMemberApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRefSetMemberParameterizedTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRefSetParameterizedTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRelationshipApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/AbstractSnomedExtensionApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedComponentEffectiveTimeRestoreTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionDowngradeTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionUpgradeTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionVersioningTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedExportApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/merge/SnomedComponentRevisionConflictProcessor.java
  tests/com.b2international.snowowl.test.commons/META-INF/MANIFEST.MF
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/json/JsonExtensions.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/rest/RestExtensions.java
Labels: feature

#741 [server] Capture reference to Framework instance while it is running
  core/com.b2international.snowowl.server.product/src/com/b2international/snowowl/server/product/SnowOwlServerActivator.java
Labels: bug

#740 [classification] Infer grouped additional properties without participating in redundancy tests
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/ConcreteDomainFragment.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/StatementFragment.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedOWLRelationshipDocument.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/taxonomy/ReasonerTaxonomyBuilder.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormGenerator.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormGroup.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormGroupSet.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormProperty.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormRelationship.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormUnionGroup.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormValue.java
Labels: feature

#468 SDD-788 support ELK based classifications in SDD
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/taxonomy/ReasonerTaxonomyBuilder.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/classification/ClassificationTracker.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/classification/ClassifyOperation.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/equivalence/EquivalencyChecker.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationCreateRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationCreateRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationJobRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationJobRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/OntologyExportRequest.java
Labels: pinned

#745 Bump Tycho to 2.2.0
  pom.xml
Labels: enhancement

#747 SDD-973: Improve classification save performance
  snomed/com.b2international.snowowl.snomed.importer.rf2/src/com/b2international/snowowl/snomed/importer/rf2/terminology/SnomedConceptImporter.java
Labels: enhancement

#751 SO-4641: Add moduleId to StatementFragment
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/StatementFragment.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedOWLRelationshipDocument.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/taxonomy/ReasonerTaxonomyBuilder.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormGenerator.java
Labels: enhancement
