Repository b2ihealthcare/snow-owl, pull requests merged in 2021-07, with the labels that each got.

#837 SO-4731: Update ECL to version 1.5
  releng/target-platform/target-platform.target
  snomed/com.b2international.snowowl.snomed.core.feature/feature.xml
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedConceptRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedExpressionLabelService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/domain/SnomedConceptRestSearch.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/.launch/snomed-core-unit-tests.launch
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequestTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclLabelerRequestTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ql/SnomedQueryEvaluationRequestTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/AllSnomedDatastoreTests.java
  snomed/com.b2international.snowowl.snomed.datastore/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/SnomedPlugin.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/LabeledEclExpressions.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclLabelerRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclLabelerRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRefinementEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRewriter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/DefaultSnomedQueryParser.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/DefaultSnomedQuerySerializer.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/Expressions.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/SnomedQueryEvaluationRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/SnomedQueryEvaluationRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/SnomedQueryExpression.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ql/SnomedQuerySerializer.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/request/SnomedConceptSearchRequestEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/EvaluateQueryRefSetMemberRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedQueryMemberCreateDelegate.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRequests.java
Labels: enhancement

#848 SO-4730: Upgrade Elasticsearch to 7.13.3
  commons/com.b2international.index/.classpath
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/pom.xml
  commons/com.b2international.index/src/com/b2international/index/Activator.java
  commons/com.b2international.index/src/com/b2international/index/es/admin/EsIndexAdmin.java
  commons/com.b2international.index/src/com/b2international/index/es/client/IndicesClient.java
  commons/com.b2international.index/src/com/b2international/index/es/client/http/EsHttpClient.java
  commons/com.b2international.index/src/com/b2international/index/es/client/http/IndicesHttpClient.java
  commons/com.b2international.index/src/com/b2international/index/es/client/tcp/IndicesTcpClient.java
  commons/com.b2international.index/src/com/b2international/index/mapping/DocumentMapping.java
Labels: enhancement

#849 SO-4882: Upgrade empty extension bug
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionBranchMergeTest.java
  commons/com.b2international.index/src/com/b2international/index/revision/BaseRevisionBranching.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeSynchronizationRequest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionUpgradeTest.java
Labels: bug

#851 Add base terminology resource requests
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/bundle/BundleApiTest.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/BundleApiAssert.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/CodeSystemApiAssert.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/bundle/BundleRestApiTest.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemApiTest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemCreateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemCreateRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpdateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpdateRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceUpdateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseTerminologyResourceCreateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseTerminologyResourceUpdateRequest.java
Labels: enhancement

#853 Pull up OID filter ResourceRestSearch
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemRestSearch.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/resource/ResourceRestSearch.java
Labels: enhancement

#854 Resource update request URL validation
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceUpdateRequest.java
Labels: bug

#855 SO-4891: multi-value expand parameter support
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/bundle/BundleRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/commit/CommitInfoRestSearch.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/commit/RepositoryCommitRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/domain/ObjectRestSearch.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/domain/ResourceSelectors.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/resource/ResourceRestService.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/IndexResourceRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedClassificationRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedConceptRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedDescriptionRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedReferenceSetMemberRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedReferenceSetRestService.java
Labels: enhancement

#857 SO- 4890: support includeNull and pretty query parameters
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/SnowOwlApiConfig.java
  fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/tests/FhirTest.java
Labels: feature

#858 SO-4892: field selection support
  commons/com.b2international.index/src/com/b2international/index/es/EsDocumentSearcher.java
  commons/com.b2international.index/src/com/b2international/index/mapping/DocumentMapping.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/bundle/BundleRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/VersionRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/commit/RepositoryCommitRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/domain/ResourceSelectors.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/resource/ResourceRestService.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/commit/CommitInfo.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/BaseComponent.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptSearchRequestEvaluator.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchIndexResourceRequest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AbstractSnomedApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedPartialLoadingApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedComponentEffectiveTimeRestoreTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionUpgradeTest.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedClassificationRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedConceptRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedDescriptionRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedReferenceSetMemberRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedReferenceSetRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedRelationshipRestService.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedConcept.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedDescription.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedRelationship.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/request/SnomedConceptSearchRequestEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedReferenceSetMemberConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedConceptDocument.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequest.java
Labels: feature

#859 Add filter by resource type to version get request
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/VersionRestSearch.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/VersionRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/request/BulkActionResolver.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/request/ResourceAction.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRefSetMemberApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/request/RefSetMemberRequestResolver.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/request/RefSetRequestResolver.java
Labels: enhancement

#860 Add API to import multiple resources from single file
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ResourcesExportRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ResourcesExportRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/io/ResourcesImportRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/io/ResourcesImportRequestBuilder.java
Labels: enhancement

#862 Fix variable names
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptMapSearchRequestEvaluator.java
  snomed/com.b2international.snowowl.snomed.fhir/src/com/b2international/snowowl/snomed/fhir/SnomedConceptMapApiProvider.java
Labels: enhancement

#863 feat: support synonym filter in tokenized analyzer configurations
  commons/com.b2international.index.tests.tools/src/com/b2international/index/SynonymsRule.java
  commons/com.b2international.index.tests/src/com/b2international/index/AnalyzerTest.java
  commons/com.b2international.index/src/com/b2international/index/Analyzers.java
  commons/com.b2international.index/src/com/b2international/index/es/EsIndexClientFactory.java
  commons/com.b2international.index/src/com/b2international/index/es/EsNode.java
  commons/com.b2international.index/src/com/b2international/index/es/admin/analysis.json
  commons/com.b2international.index/src/com/b2international/index/query/TextPredicate.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/ResourceDocument.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/jobs/RemoteJobEntry.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/issue/ValidationIssue.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/whitelist/ValidationWhiteList.java
  docker/config/analysis/synonym.txt
  docker/docker-compose.yml
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedDescriptionIndexEntry.java
Labels: feature

#868 SO-4896: Numeric relationship values update
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedRestFixtures.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/classification/SnomedClassificationApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConcreteValueApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/domain/SnomedRelationshipRestInput.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/domain/SnomedRelationshipRestUpdate.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequestTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRelationshipIndexEntrySerializationTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/RelationshipValue.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/RelationshipValueType.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedRelationship.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRefinementEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/StatementFragmentWithValue.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedOWLRelationshipDocument.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRefSetMemberIndexEntry.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRelationshipIndexEntry.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/taxonomy/ReasonerTaxonomyBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedOWLExpressionConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRefSetMemberSearchRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/importer/Rf2ConcreteValueContentType.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/importer/Rf2EffectiveTimeSlice.java
  snomed/com.b2international.snowowl.snomed.fhir/src/com/b2international/snowowl/snomed/fhir/SnomedCodeSystemApiProvider.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/RelationshipChangeConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/diff/relationship/RelationshipWriter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/diff/relationship/StatementFragmentOrdering.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/domain/ReasonerRelationship.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/index/RelationshipChangeDocument.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormGenerator.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/normalform/NormalFormValue.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/ontology/DelegateOntology.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/snomed/DocumentBuilders.java
Labels: enhancement
