Repository b2ihealthcare/snow-owl, pull requests merged in 2021-09, with the labels that each got.

#889 SO-4917: Move settings keys to the domain class
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystem.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/version/VersioningRequest.java
Labels: enhancement

#891 SO-4923: Index ancestor bundle identifiers on resources
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranch.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/bundle/BundleApiTest.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/bundle/BundleRestApiTest.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/domain/BaseResourceRestSearch.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/resource/ResourceRestService.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/Resource.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/TerminologyResource.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/bundle/Bundle.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/bundle/BundleDeleteRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystem.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/ResourceDocument.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceCreateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceSearchRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceUpdateRequest.java
Labels: feature

#893 SNRAY-329: Fix missing semantic tags on concept documents
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/change/BaseChangeProcessorTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/change/ConceptIconIdUpdaterTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/change/PreferredDescriptionPreCommitHookTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ConceptChangeProcessor.java
Labels: bug

#900 RF2 export field selection
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchIndexResourceRequest.java
  snomed/com.b2international.snowowl.snomed.common/src/com/b2international/snowowl/snomed/common/SnomedRf2Headers.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedApiTestConstants.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedRestFixtures.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRefSetMemberApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRefSetMemberParameterizedTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedExportApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedImportApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRefSetMemberDocumentSerializationTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/RelationshipValue.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedRelationship.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/store/SnomedMRCMDomainReferenceSetMemberBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRefSetMemberIndexEntry.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedMRCMDomainMemberCreateDelegate.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedMRCMDomainMemberUpdateDelegate.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRelationshipSearchRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/exporter/Rf2Exporter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/exporter/Rf2RefSetDescriptorRefSetExporter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/importer/Rf2MRCMDomainRefSetContentType.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/importer/Rf2TransactionContext.java
Labels: enhancement

#902 fix(snomed): replace deprecated method calls to `all()` with...
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchPageableCollectionResourceRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRefinementEvaluator.java
Labels: enhancement

#903 SO-4934: Deprecate scrolling search
  commons/com.b2international.index.tests.tools/src/com/b2international/index/BaseIndexTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/StreamTest.java
  commons/com.b2international.index/src/com/b2international/index/Hits.java
  commons/com.b2international.index/src/com/b2international/index/Scroll.java
  commons/com.b2international.index/src/com/b2international/index/SearchAfterIterator.java
  commons/com.b2international.index/src/com/b2international/index/Searcher.java
  commons/com.b2international.index/src/com/b2international/index/es/EsDocumentSearcher.java
  commons/com.b2international.index/src/com/b2international/index/es/client/EsClient.java
  commons/com.b2international.index/src/com/b2international/index/es/client/http/EsHttpClient.java
  commons/com.b2international.index/src/com/b2international/index/es/client/tcp/EsTcpClient.java
  commons/com.b2international.index/src/com/b2international/index/query/DefaultQueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/query/Query.java
  commons/com.b2international.index/src/com/b2international/index/query/SortBy.java
  commons/com.b2international.index/src/com/b2international/index/revision/DefaultRevisionSearcher.java
  commons/com.b2international.index/src/org/elasticsearch/client/RestHighLevelClientExt.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/validation/ValidationRepository.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/jobs/RemoteJobTracker.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/RepositoryTransactionContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/RevisionIndexReadRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRefinementEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/version/SnomedVersioningRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ComponentInactivationChangeProcessor.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/DetachedContainerChangeProcessor.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/taxonomy/ReasonerTaxonomyBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptUpdateRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/validation/SnomedQueryValidationRuleEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/validation/detail/SnomedValidationIssueDetailExtension.java
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule110.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule34.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule482.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule55.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule663.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule664.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule665.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule666.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule667.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule668.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule669.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule671.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule75.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint_type.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_stated_mrcm_constraint.groovy
  snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_stated_mrcm_constraint_type.groovy
Labels: feature

#907 SO-4942: Support delta RF2 exports with branch path range
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedExportApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ExportRequest.java
Labels: feature

#871 SO-4896: Numeric relationship values update (8.x)
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConcreteValueApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/domain/SnomedRelationshipRestInput.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/domain/SnomedRelationshipRestUpdate.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequestTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedRelationship.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRefinementEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedOWLRelationshipDocument.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedRelationshipIndexEntry.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/taxonomy/ReasonerTaxonomyBuilder.java
  snomed/com.b2international.snowowl.snomed.fhir/src/com/b2international/snowowl/snomed/fhir/SnomedFhirCodeSystemLookupConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
Labels: enhancement
