Repository b2ihealthcare/snow-owl, pull requests merged in 2022-01, with the labels that each got.

#961 refactor(core): Clarify that resources store bundle ancestor IDs...
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/resource/ResourceApiTest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/Resource.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/bundle/Bundle.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/ResourceDocument.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceCreateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceUpdateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ResourceConverter.java
Labels: feature

#962 feat(core): Introduce streaming helper method that uses the...
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchPageableCollectionResourceRequestBuilder.java
Labels: enhancement

#956 chore(deps): upgrade elasticsearch to 7.16.3...
  commons/com.b2international.index/.classpath
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/lib/elasticsearch-log4j-7.16.1.jar
  commons/com.b2international.index/lib/elasticsearch-log4j-7.16.3.jar
  commons/com.b2international.index/pom.xml
  docker/docker-compose.yml
Labels: enhancement

#957 [7.x] chore(deps): upgrade elasticsearch to 7.16.3 and log4j to 2.17.1
  commons/com.b2international.index/.classpath
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/lib/elasticsearch-log4j-7.16.1.jar
  commons/com.b2international.index/lib/elasticsearch-log4j-7.16.3.jar
  commons/com.b2international.index/pom.xml
  docker/docker-compose.yml
Labels: enhancement

#966 feat(api): support expansion of `commits()` in Resource API
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/Resource.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/TerminologyResource.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ResourceConverter.java
Labels: feature

#967 feat(core): support resource expansion via plugins
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/bundle/BundleConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/commit/CommitInfoConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceExpander.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/DescendantsExpander.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ResourceConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ResourceExpander.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedConceptConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedDescriptionConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedReferenceSetConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedReferenceSetMemberConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedRelationshipConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/ClassificationTaskConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/ConceptChangeConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/ConcreteDomainChangeConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/DescriptionChangeConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/EquivalentConceptSetConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/RelationshipChangeConverter.java
Labels: feature

#970 Fix: Snomed expanded properties are missing
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptSearchApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptCachingRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptRequestCache.java
Labels: bug

#971 fix(auth): prevent access to resources when permissions claim is empty..
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/auth/AuthorizationTest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceSearchRequest.java
Labels: bug
