Repository b2ihealthcare/snow-owl, pull requests merged in 2022-05, with the labels that each got.

#1014 feat(snomed): Add immediate mode to SnomedConceptRequestCache for tests
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/ModuleExpander.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedConceptConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedDescriptionConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedRelationshipConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptRequestCache.java
Labels: enhancement

#1015 fix(index): Defer "must" and "filter" clause reduction to a later...
  commons/com.b2international.index.tests/src/com/b2international/index/BoolQueryTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/Fixtures.java
  commons/com.b2international.index/src/com/b2international/index/es/query/EsQueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/query/AbstractExpressionBuilder.java
Labels: bug

#1021 feat(eventbus): Enable call-time stack trace recording with JVM option
  netty/com.b2international.snowowl.eventbus/src/com/b2international/snowowl/eventbus/IEventBus.java
  netty/com.b2international.snowowl.eventbus/src/com/b2international/snowowl/internal/eventbus/EventBus.java
Labels: enhancement

#1022 fix(core): Make derived field on User transient
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/User.java
Labels: bug

#1027 feat(core.rest): Add support for search code systems by URL
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/resource/TerminologyResourceRestSearch.java
Labels: enhancement

#1026 Authorization API improvements
  cis/com.b2international.snowowl.snomed.cis.rest/src/com/b2international/snowowl/snomed/cis/rest/CisBulkSctIdService.java
  commons/com.b2international.index.test.tools/.classpath
  commons/com.b2international.index.test.tools/META-INF/MANIFEST.MF
  commons/com.b2international.index.test.tools/build.properties
  commons/com.b2international.index.test.tools/pom.xml
  core/com.b2international.snowowl.core.rest.tests/.launch/core-e2e-tests.launch
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/auth/AuthorizationTest.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/bundle/BundleRestApiTest.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemApiTest.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/info/RepositoryApiTest.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/resource/ResourceApiTest.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/admin/RepositoryRestService.java
  core/com.b2international.snowowl.core.tests/.launch/core-unit-tests.launch
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/authorization/AccessControl.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/authorization/AuthorizationService.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/authorization/AuthorizedRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/AbstractBranchChangeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeSynchronizationRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/console/CommandLineAuthenticator.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/AdminPartyIdentityProvider.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/AuthorizationHeaderVerifier.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/DefaultJWTGenerator.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/IdentityProvider.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/Role.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/User.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/file/FileIdentityProvider.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/jobs/RemoteJob.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/jobs/ScheduleJobRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/DefaultOperationLockManager.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/Locks.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/LocksCommand.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/request/LockChangeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/monitoring/MonitoredRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/rate/RateLimitingRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/RepositoryTransactionContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceCreateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/version/VersionCreateRequest.java
  core/com.b2international.snowowl.identity.ldap/src/com/b2international/snowowl/identity/ldap/LdapCommand.java
  core/com.b2international.snowowl.identity.ldap/src/com/b2international/snowowl/identity/ldap/LdapIdentityProvider.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/branch/SnomedBranchRequestTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/io/commit/SnomedCommitApiAuthorizationTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationCreateRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationSaveRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
  tests/com.b2international.snowowl.test.commons/META-INF/MANIFEST.MF
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/auth/BaseAuthorizationTest.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/rest/BundleApiAssert.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/rest/CodeSystemApiAssert.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/rest/RepositoryApiAssert.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/rest/ResourceApiAssert.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/rest/RestExtensions.java
  tests/com.b2international.snowowl.test.dependencies/.classpath
  tests/com.b2international.snowowl.test.dependencies/META-INF/MANIFEST.MF
  tests/com.b2international.snowowl.test.dependencies/build.properties
  tests/com.b2international.snowowl.test.dependencies/lib/.gitignore
  tests/com.b2international.snowowl.test.dependencies/pom.xml
  tests/com.b2international.snowowl.test.dependencies/src/com/b2international/snowowl/rules/LazyEnvironmentVariables.java
Labels: feature
