Repository b2ihealthcare/snow-owl, pull requests merged in 2022-04, with the labels that each got.

#1001 Wrap Groovy 3.0.9 and extensions into a bundle
  commons/com.b2international.groovy/.classpath
  commons/com.b2international.groovy/.project
  commons/com.b2international.groovy/META-INF/MANIFEST.MF
  commons/com.b2international.groovy/build.properties
  commons/com.b2international.groovy/lib/.gitignore
  commons/com.b2international.groovy/pom.xml
  commons/pom.xml
  core/com.b2international.snowowl.core.dependencies.feature/feature.xml
  core/com.b2international.snowowl.core/META-INF/MANIFEST.MF
  releng/target-platform/target-platform.target
  snomed/com.b2international.snowowl.validation.snomed/META-INF/MANIFEST.MF
  tests/com.b2international.snowowl.test.commons/META-INF/MANIFEST.MF
Labels: enhancement

#1002 fix(api): commits endpoint authorization now correctly restricts...
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/commit/CommitInfoSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/Permission.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/io/commit/CommitInfoRequestTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/io/commit/SnomedCommitApiAuthorizationTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/io/commit/SnomedCommitApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/request/ConceptMapSearchMappingRequestSnomedMapTypeReferenceSetTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AllSnomedApiTests.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptMapSearchRequestEvaluator.java
Labels: bug

#1003 Expose Elastic Search score
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedComponent.java
Labels: enhancement

#1008 Support Elasticsearch 8 clusters
  commons/com.b2international.commons/src/com/b2international/commons/TokenReplacer.java
  commons/com.b2international.commons/src/com/b2international/commons/collections/Procedure.java
  commons/com.b2international.commons/src/com/b2international/commons/http/AcceptHeader.java
  commons/com.b2international.commons/src/com/b2international/commons/options/HashMapOptions.java
  commons/com.b2international.index.test.tools/.classpath
  commons/com.b2international.index.test.tools/META-INF/MANIFEST.MF
  commons/com.b2international.index.test.tools/build.properties
  commons/com.b2international.index.test.tools/lib/.gitignore
  commons/com.b2international.index.test.tools/pom.xml
  commons/com.b2international.index.test.tools/src/com/b2international/index/IndexResource.java
  commons/com.b2international.index.tests/.launch/index-http-unit-tests (es8).launch
  commons/com.b2international.index.tests/META-INF/MANIFEST.MF
  commons/com.b2international.index.tests/pom.xml
  commons/com.b2international.index.tests/src/com/b2international/index/RegExpQueryTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/SortIndexTest.java
  commons/com.b2international.index/.classpath
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/lib/elasticsearch-log4j-7.17.2.jar
  commons/com.b2international.index/pom.xml
  commons/com.b2international.index/src/com/b2international/index/IndexClientFactory.java
  commons/com.b2international.index/src/com/b2international/index/es/EsClientConfiguration.java
  commons/com.b2international.index/src/com/b2international/index/es/EsIndexClientFactory.java
  commons/com.b2international.index/src/com/b2international/index/es/admin/EsIndexAdmin.java
  commons/com.b2international.index/src/com/b2international/index/es/client/http/EsHttpClient.java
  commons/com.b2international.index/src/com/b2international/index/es/query/EsQueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/mapping/DocumentMapping.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionConflictProcessor.java
  core/com.b2international.snowowl.core.tests/src/com/b2international/snowowl/core/events/util/PromiseTest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/config/IndexConfiguration.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/console/RepositoriesCommand.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/events/util/Promise.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/merge/MergeConflict.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ecl/AbstractComponentSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ecl/EclEvaluationRequest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/.launch/snomed-e2e-tests (es8).launch
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/perf/SnomedRebaseVsClassificationIssueTest.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/services/SnomedComponentOrdering.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedConcept.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/refset/SnomedReferenceSetMember.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/refset/SnomedReferenceSetMembers.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/EclExpression.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRefinementEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/tree/TerminologyTree.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/SnomedRefSetMemberFragment.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedReferenceSetMemberConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/entry/SnomedDescriptionIndexEntry.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/EvaluateQueryRefSetRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/RelationshipChangeConverter.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/SnowOwlAppRule.java
Labels: enhancement, feature
