Repository b2ihealthcare/snow-owl, pull requests merged in 2023-12, with the labels that each got.

#1247 fix(fhir): Remove CapabilityStatement and its "read" interaction from...
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirMetadataController.java
Labels: bug

#1249 SO-4122: index schema migration support
  commons/com.b2international.index.test.tools/src/com/b2international/index/BaseIndexTest.java
  commons/com.b2international.index.test.tools/src/com/b2international/index/IndexResource.java
  commons/com.b2international.index.test.tools/src/com/b2international/index/revision/BaseRevisionIndexTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/BoolQueryTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/NestedDocumentIndexTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/ShardConfigurationTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/mapping/MappingMigrationTest.java
  commons/com.b2international.index/src/com/b2international/index/Doc.java
  commons/com.b2international.index/src/com/b2international/index/IndexException.java
  commons/com.b2international.index/src/com/b2international/index/SearchContextMissingException.java
  commons/com.b2international.index/src/com/b2international/index/Writer.java
  commons/com.b2international.index/src/com/b2international/index/admin/IndexAdmin.java
  commons/com.b2international.index/src/com/b2international/index/es/EsDocumentSearcher.java
  commons/com.b2international.index/src/com/b2international/index/es/EsDocumentWriter.java
  commons/com.b2international.index/src/com/b2international/index/es/EsIndexClient.java
  commons/com.b2international.index/src/com/b2international/index/es/admin/EsIndexAdmin.java
  commons/com.b2international.index/src/com/b2international/index/es/admin/IndexMapping.java
  commons/com.b2international.index/src/com/b2international/index/es/reindex/ReindexResult.java
  commons/com.b2international.index/src/com/b2international/index/mapping/DocumentMapping.java
  commons/com.b2international.index/src/com/b2international/index/mapping/Mappings.java
  commons/com.b2international.index/src/com/b2international/index/migrate/DocumentMappingMigrationStrategy.java
  commons/com.b2international.index/src/com/b2international/index/migrate/DocumentMappingMigrator.java
  commons/com.b2international.index/src/com/b2international/index/migrate/SchemaRevision.java
  commons/com.b2international.index/src/com/b2international/index/revision/DefaultRevisionIndex.java
  commons/com.b2international.index/src/com/b2international/index/revision/DefaultRevisionWriter.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranchChangeSet.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionIndexAdmin.java
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  core/com.b2international.snowowl.core.tests/src/com/b2international/snowowl/core/locks/LockIndexTests.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/RepositoryTransactionContext.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/merge/SnomedComponentRevisionConflictProcessor.java
Labels: feature

#1250 SO-4122: Implement index schema migrators
  commons/com.b2international.index.tests/src/com/b2international/index/mapping/MappingMigrationTest.java
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/src/com/b2international/index/IndexClientFactory.java
  commons/com.b2international.index/src/com/b2international/index/Writer.java
  commons/com.b2international.index/src/com/b2international/index/admin/IndexAdmin.java
  commons/com.b2international.index/src/com/b2international/index/es/EsDocumentWriter.java
  commons/com.b2international.index/src/com/b2international/index/es/HitConverter.java
  commons/com.b2international.index/src/com/b2international/index/es/admin/EsIndexAdmin.java
  commons/com.b2international.index/src/com/b2international/index/es/admin/IndexMapping.java
  commons/com.b2international.index/src/com/b2international/index/migrate/DocumentMappingMigrator.java
  commons/com.b2international.index/src/com/b2international/index/revision/Commit.java
  commons/com.b2international.index/src/com/b2international/index/revision/DefaultRevisionIndex.java
  commons/com.b2international.index/src/com/b2international/index/revision/DefaultRevisionWriter.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranch.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/ResourceDocument.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/ResourceDocumentSchemaMigratorV9_0.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/issue/ValidationIssue.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/version/VersionDocument.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/version/VersionDocumentSchemaMigratorV9_0.java
Labels: feature

#1252 chore(deps): bump elasticsearch dependencies to 7.17.16
  commons/com.b2international.index/.classpath
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/pom.xml
Labels: enhancement
