Repository b2ihealthcare/snow-owl, pull requests merged in 2023-11, with the labels that each got.

#1216 feat(fhir): Add "after" and "next" properties to value set expansions
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/model/valueset/expansion/Expansion.java
  fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/rest/tests/valueset/FhirValueSetSnomedExpandTest.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirValueSetExpandOperationController.java
Labels: enhancement

#1236 refactor(api): extract sort pattern generation to SortSupport helper
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/AbstractRestService.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/SortSupport.java
Labels: enhancement

#1186 refactor(snomed.datastore): Improve SnomedDescendantsExpander
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedDescendantsExpander.java
Labels: enhancement

#1237 SO-5925: Support collecting auxiliary analysis components
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/compare/AnalysisCompareResult.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/compare/AnalysisCompareResultItem.java
Labels: enhancement

#1241 SO-3916: set definition status to primitive regardless of user choice
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptInactivationApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptUpdateRequest.java
Labels: bug

#1239 SO-5919: Return access token as part of User object on login
  cis/com.b2international.snowowl.snomed.cis.rest/src/com/b2international/snowowl/snomed/cis/rest/CisAuthenticationService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/admin/AuthorizationService.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/client/TransportClient.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/User.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/request/UserLoginRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/identity/request/UserLoginRequestBuilder.java
Labels: bug, enhancement

#1170 fix(index): Revise merged revisions to avoid duplication
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
Labels: bug, port-to-7.x, on hold

#1173 fix(index): Revise merged revisions to avoid duplication (7.x)
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedRestFixtures.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionUpgradeTest.java
Labels: bug, on hold

#1225 SO-5913: Prevent unnecessary post processing during versioning (9.x)
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/BaseRepositoryPreCommitHook.java
Labels: enhancement

#1246 feat: make validation jobs cancellable
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/ServiceProvider.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/ValidateRequest.java
Labels: enhancement
