Repository b2ihealthcare/snow-owl, pull requests merged in 2023-05, with the labels that each got.

#1149 Resolve issue when deleting directories with multiple sub-directories
  commons/com.b2international.commons.test/src/com/b2international/commons/test/io/PathUtilsTests.java
  commons/com.b2international.commons/src/com/b2international/commons/io/PathUtils.java
Labels: port-to-7.x

#1153 fix(core): properly expand preferred display for concept maps...
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptMapMappingSearchRequest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/request/ConceptMapSearchMappingRequestSnomedMapTypeReferenceSetTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptMapSearchRequestEvaluator.java
Labels: bug

#1154 Short ipv6 format parsing from doc values
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionBranchMergeTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionBranchPointTest.java
  commons/com.b2international.index/src/com/b2international/index/revision/Commit.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranchPoint.java
Labels: bug, port-to-7.x

#1155 ES query profiling per request
  commons/com.b2international.commons/META-INF/MANIFEST.MF
  commons/com.b2international.commons/src/com/b2international/commons/metric/Metrics.java
  commons/com.b2international.index/src/com/b2international/index/Searcher.java
  commons/com.b2international.index/src/com/b2international/index/es/EsDocumentSearcher.java
  commons/com.b2international.index/src/com/b2international/index/query/DefaultQueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/query/Query.java
  commons/com.b2international.index/src/com/b2international/index/revision/DefaultRevisionSearcher.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/ApplicationContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/RequestContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/authorization/AuthorizedEventBus.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/RepositoryBranchContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/events/AsyncRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/events/util/RequestHeaders.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/events/util/Response.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/SnowOwlPlugin.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/monitoring/MonitoredRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/ApiRequestHandler.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BranchRealtimeContentRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchIndexResourceRequest.java
Labels: enhancement

#1156 feat(core): add generic ID uniqueness and presence check step to each...
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/DelegatingTransactionContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/RepositoryBranchContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/TransactionContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/RepositoryTransactionContext.java
Labels: enhancement

#1159 SO-5596: snapshot import with unpublished references (7.x)
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedCT_RF2Release_INT_20180223_content_w_and_wo_effective_time_mix.zip
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedImportApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequest.java
Labels: bug

#1162 fix(index): scoring issue when searching for nested analyzed fields
  commons/com.b2international.index.tests/src/com/b2international/index/Fixtures.java
  commons/com.b2international.index.tests/src/com/b2international/index/SortIndexTest.java
  commons/com.b2international.index/src/com/b2international/index/es/query/EsQueryBuilder.java
Labels: bug

#1161 SO-3933: published vs unpublished snapshot export
  cis/com.b2international.snowowl.snomed.cis/src/com/b2international/snowowl/snomed/cis/gen/SequentialItemIdGenerationStrategy.java
  commons/com.b2international.commons/src/com/b2international/commons/Pair.java
  commons/com.b2international.commons/src/com/b2international/commons/ReflectionUtils.java
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedExportRestRequests.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/SnomedRestFixtures.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedExportApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ExportRequest.java
Labels: bug
