Repository b2ihealthcare/snow-owl, pull requests merged in 2023-06, with the labels that each got.

#1160 SO-4901: identical component conflict
  commons/com.b2international.commons/src/com/b2international/commons/json/Json.java
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionBranchMergeConflictTest.java
  commons/com.b2international.index/src/com/b2international/index/revision/AddedInSourceAndDetachedInTargetConflict.java
  commons/com.b2international.index/src/com/b2international/index/revision/AddedInTargetAndDetachedInSourceConflict.java
  commons/com.b2international.index/src/com/b2international/index/revision/BaseRevisionBranching.java
  commons/com.b2international.index/src/com/b2international/index/revision/BranchMergeOperation.java
  commons/com.b2international.index/src/com/b2international/index/revision/ChangedInSourceAndDetachedInTargetConflict.java
  commons/com.b2international.index/src/com/b2international/index/revision/ChangedInSourceAndTargetConflict.java
  commons/com.b2international.index/src/com/b2international/index/revision/Conflict.java
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/branches/SnomedMergeConflictTest.java
Labels: enhancement

#1165 SO-5807: properly report validation issues as bad request instead of HTTP 500
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/exceptions/FhirException.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/AbstractFhirController.java
Labels: bug

#1166 SO-5811: fix FHIR publisher field selection
  commons/com.b2international.index.tests/src/com/b2international/index/PartialDocumentLoadingTest.java
  commons/com.b2international.index/src/com/b2international/index/es/EsDocumentSearcher.java
  commons/com.b2international.index/src/com/b2international/index/mapping/DocumentMapping.java
  fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/rest/tests/codesystem/FhirCodeSystemApiTest.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/codesystem/CodeSystemRestRequests.java
Labels: bug

#1167 SO-5807: ensure we return a full Value Set resource when expanding with members
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/valueset/FhirValueSetExpandRequest.java
Labels: bug

#1169 fix(api): ensure the same term filtering behavior as in the SNOMED CT...
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/request/SnomedConceptSearchRequestEvaluator.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequestBuilder.java
Labels: bug

#1164 SO-5804: Concept search and update request changes
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptUpdateRequest.java
Labels: enhancement

#1174 feat(fhir): Add permission check to FHIR resource update requests
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/model/Issue.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/FhirResourceUpdateRequest.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/codesystem/FhirCodeSystemUpdateRequest.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/conceptmap/FhirConceptMapUpdateRequest.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/valueset/FhirValueSetUpdateRequest.java
  fhir/com.b2international.snowowl.fhir.rest.tests/.launch/fhir-api-tests.launch
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/AbstractFhirController.java
Labels: bug

#1181 fix(fhir): add a separate `X-Owner` header to configure ownership...
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/codesystem/FhirCodeSystemUpdateRequest.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/codesystem/FhirCodeSystemUpdateRequestBuilder.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/codesystem/FhirCodeSystemWriteSupport.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/conceptmap/FhirConceptMapUpdateRequest.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/conceptmap/FhirConceptMapUpdateRequestBuilder.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/conceptmap/FhirConceptMapWriteSupport.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/valueset/FhirValueSetUpdateRequest.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/valueset/FhirValueSetUpdateRequestBuilder.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/request/valueset/FhirValueSetWriteSupport.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/AbstractFhirController.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirCodeSystemController.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirConceptMapController.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirValueSetController.java
Labels: bug, enhancement

#1182 Collect nested requests for permission checking recursively in TransactionalRequest and SnomedBulkRequest
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/TransactionalRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedBulkRequest.java
Labels: bug

#1184 fix(index): support loading unindexed fields from documents
  commons/com.b2international.index.tests/src/com/b2international/index/Fixtures.java
  commons/com.b2international.index.tests/src/com/b2international/index/PartialDocumentLoadingTest.java
  commons/com.b2international.index/src/com/b2international/index/es/EsDocumentSearcher.java
  commons/com.b2international.index/src/com/b2international/index/mapping/DocumentMapping.java
Labels: bug
