Repository b2ihealthcare/snow-owl, pull requests merged in 2023-01, with the labels that each got.

#1098 SO-5580: Fix effective time restoration following status changes (8.x)
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRefSetMemberApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ComponentEffectiveTimeRestoreChangeProcessor.java
Labels: bug, port-8.x

#1097 SO-5580: Fix effective time restoration following status changes (7.x)
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRefSetMemberApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ComponentEffectiveTimeRestoreChangeProcessor.java
Labels: bug

#1103 Upgrade Eclipse Platform dependencies
  cis/com.b2international.snowowl.snomed.cis.feature/feature.xml
  cis/com.b2international.snowowl.snomed.cis.product/.launch/snow-owl-cis.launch
  cis/com.b2international.snowowl.snomed.cis.product/assembly/common/bin/cis.bat
  cis/com.b2international.snowowl.snomed.cis.product/assembly/common/bin/cis.sh
  cis/com.b2international.snowowl.snomed.cis.product/assembly/common/configuration/jetty-deploy.xml
  cis/com.b2international.snowowl.snomed.cis.product/assembly/common/configuration/jetty-http.xml
  cis/com.b2international.snowowl.snomed.cis.product/assembly/common/configuration/jetty.xml
  cis/com.b2international.snowowl.snomed.cis.product/assembly/common/configuration/serviceability.xml
  cis/com.b2international.snowowl.snomed.cis.product/snow-owl-cis.product
  cis/com.b2international.snowowl.snomed.cis/META-INF/MANIFEST.MF
  commons/com.b2international.collections.api/META-INF/MANIFEST.MF
  commons/com.b2international.commons.test/.launch/commons-tests.launch
  commons/com.b2international.index.es8/META-INF/MANIFEST.MF
  commons/com.b2international.index.test.tools/META-INF/MANIFEST.MF
  commons/com.b2international.index.tests/.launch/index-http-unit-tests (es8).launch
  commons/com.b2international.index.tests/.launch/index-http-unit-tests.launch
  commons/com.b2international.index.tests/.launch/index-tcp-unit-tests.launch
  commons/com.b2international.index/META-INF/MANIFEST.MF
  commons/com.b2international.index/src/com/b2international/index/es/admin/EsIndexAdmin.java
  commons/com.b2international.mapdb/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core.dependencies.feature/feature.xml
  core/com.b2international.snowowl.core.rest.tests/.launch/core-e2e-tests.launch
  core/com.b2international.snowowl.core.rest.tests/pom.xml
  core/com.b2international.snowowl.core.rest/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core.tests/.launch/core-unit-tests.launch
  core/com.b2international.snowowl.core/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/SnowOwl.java
  core/com.b2international.snowowl.identity.ldap/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.logback.config/logback.xml
  fhir/com.b2international.snowowl.fhir.rest.tests/.launch/fhir-api-tests.launch
  fhir/com.b2international.snowowl.fhir.rest.tests/.launch/fhir-unit-tests.launch
  fhir/com.b2international.snowowl.fhir.rest.tests/pom.xml
  fhir/com.b2international.snowowl.fhir.rest/.launch/fhir-api-server.launch
  netty/com.b2international.snowowl.eventbus.tests/.launch/eventbus-unit-tests.launch
  netty/com.b2international.snowowl.eventbus/META-INF/MANIFEST.MF
  pom.xml
  releng/com.b2international.snowowl.server.update/.launch/snow-owl-oss.launch
  releng/com.b2international.snowowl.server.update/assembly/common/bin/snowowl.bat
  releng/com.b2international.snowowl.server.update/assembly/common/bin/snowowl.sh
  releng/com.b2international.snowowl.server.update/assembly/common/configuration/jetty-deploy.xml
  releng/com.b2international.snowowl.server.update/assembly/common/configuration/jetty-http.xml
  releng/com.b2international.snowowl.server.update/assembly/common/configuration/jetty.xml
  releng/com.b2international.snowowl.server.update/assembly/common/configuration/serviceability.xml
  releng/com.b2international.snowowl.server.update/snow-owl-oss.product
  releng/target-platform/target-platform.target
  snomed/com.b2international.snowowl.snomed.core.feature/feature.xml
  snomed/com.b2international.snowowl.snomed.core.rest.tests/.launch/snomed-e2e-tests (cis).launch
  snomed/com.b2international.snowowl.snomed.core.rest.tests/.launch/snomed-e2e-tests (es8).launch
  snomed/com.b2international.snowowl.snomed.core.rest.tests/.launch/snomed-e2e-tests.launch
  snomed/com.b2international.snowowl.snomed.core.rest.tests/pom.xml
  snomed/com.b2international.snowowl.snomed.datastore.tests/.launch/snomed-core-unit-tests.launch
  snomed/com.b2international.snowowl.snomed.datastore/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.reasoner.tests/.launch/snomed-reasoner-unit-tests.launch
  snomed/com.b2international.snowowl.validation.snomed/.launch/validation-snomed-tests.launch
  tests/com.b2international.snowowl.test.commons/META-INF/MANIFEST.MF
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/BundleStartRule.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/rest/RestExtensions.java
Labels: bug, enhancement
