Repository b2ihealthcare/snow-owl, pull requests merged in 2023-09, with the labels that each got.

#1198 feat(core): Support ResourceURI input for lock/unlock requests
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/request/LockRequests.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/request/ResourceLockChangeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/request/ResourceLockChangeRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/commit/SnomedCommitApiAuthorizationTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/commit/SnomedCommitApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/request/ResourceLockRequestTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AllSnomedApiTests.java
Labels: feature

#1197 SO-5843: Support high-level resource comparisons
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/validation/RepositoryValidationRestService.java
  core/com.b2international.snowowl.core.tests/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core.tests/src/com/b2international/snowowl/core/validation/issue/ValidationIssueApiTest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/ResourceURIWithQuery.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemGetRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/compare/AnalysisCompareChangeKind.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/compare/AnalysisCompareResult.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/compare/AnalysisCompareResultItem.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/compare/DependencyComparer.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/compare/ResourceContentComparer.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/TerminologyRepositoryPlugin.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/GetResourceRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/IndexResourceRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ResourceRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ResourceRequests.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/BaseGetResourceRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/BaseGetResourceRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/BaseTerminologyResourceCreateRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/DependencyCompareRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/DependencyCompareRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/ResourceContentCompareRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/ResourceContentCompareRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/ResourceGetRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/ResourceGetRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/SuggestedAction.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/SuggestedComponent.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/ValidateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/ValidateRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/ValidationDeleteNotification.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/ValidationIssueDetails.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/ValidationRequests.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/issue/ValidationIssue.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/issue/ValidationIssueDeleteRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/issue/ValidationIssueDeleteRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/issue/ValidationIssueDetailExtension.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/issue/ValidationIssueSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/validation/issue/ValidationIssueSearchRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/request/SnomedDependencyCompareTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AllSnomedApiTests.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/SnomedDependencyComparer.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/SnomedPlugin.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/validation/detail/SnomedValidationIssueDetailExtension.java
Labels: feature

#1201 feat(core): Propagate timestamp ranges in commit expansion
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/TerminologyResource.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/BaseMetadataResourceConverter.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/request/ResourceSearchRequestTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AllSnomedApiTests.java
Labels: enhancement

#1205 SO-5904: ECL search disable synonym token filter
  commons/com.b2international.index/src/com/b2international/index/query/TextPredicate.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ecl/EclEvaluationRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/search/MatchTermFilter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/search/TermFilter.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequestPropertyFilterTest.java
Labels: bug, port-to-8.x

#1206 SO-5905: ECL wild lexical search type should be case insensitive
  commons/com.b2international.index/src/com/b2international/index/es/query/Es8QueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/es/query/EsQueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/query/Expressions.java
  commons/com.b2international.index/src/com/b2international/index/query/RegexpPredicate.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ecl/EclEvaluationRequest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequestPropertyFilterTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequest.java
Labels: bug, port-to-8.x

#1207 SO-5904: disable synonym token filter during ECL searches
  README.md
  commons/com.b2international.index/src/com/b2international/index/query/TextPredicate.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ecl/EclEvaluationRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/search/MatchTermFilter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/search/TermFilter.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequestPropertyFilterTest.java
Labels: bug

#1208 SO-5905: wild matches should be case insensitive
  commons/com.b2international.index/src/com/b2international/index/es/query/Es8QueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/es/query/EsQueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/query/Expressions.java
  commons/com.b2international.index/src/com/b2international/index/query/RegexpPredicate.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ecl/EclEvaluationRequest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequestPropertyFilterTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequest.java
Labels: bug

#1209 feat(index): support branch name and path aliases
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionBranchPathAliasTest.java
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionBranchingTest.java
  commons/com.b2international.index/src/com/b2international/index/revision/BaseRevisionBranching.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranch.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/BranchUpdateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/BranchUpdateRequestBuilder.java
Labels: feature

#1211 SO-5877: core API changes necessary for the new upgrade flow
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranch.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemApiDependencyTest.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/resource/TerminologyResourceCollectionApiTest.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemRestCreate.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemRestService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemUpdateRestInput.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/TerminologyResource.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/api/IBranchPath.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/BranchSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/bundle/BundleConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystem.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemCreateRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemSearchRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemSearchRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpdateRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeState.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeSynchronizationRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeSynchronizationRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/UpgradeInfo.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/collection/TerminologyResourceCollectionConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/collection/TerminologyResourceCollectionResourceTypeConverter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/console/CodeSystemsCommand.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/ResourceDocument.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/BaseResourceSearchRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/BaseTerminologyResourceCreateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/resource/BaseTerminologyResourceUpdateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/version/VersionCreateRequest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConcreteValueApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedDescriptionApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedRelationshipApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/AbstractSnomedExtensionApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedComponentEffectiveTimeRestoreTest.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/ApiTestConstants.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/SnomedContentRule.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/codesystem/CodeSystemRestRequests.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/codesystem/CodeSystemVersionRestRequests.java
Labels: feature

#1212 feat(core): improved lock context propagation support
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/admin/RepositoryRestService.java
  core/com.b2international.snowowl.core.tests/src/com/b2international/snowowl/core/locks/DatastoreLockTests.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/TerminologyResource.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/BranchMergeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/branch/BranchRebaseRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/locks/DatastoreLockTarget.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/locks/RemoteLockTargetListener.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/locks/Slf4jOperationLockTargetListener.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/AbstractOperationLock.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/DefaultOperationLockManager.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/IOperationLock.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/IOperationLockManager.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/IOperationLockTargetListener.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/Lockable.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/Locks.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/LocksCommand.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/OperationLock.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/OperationLockInfo.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/request/AbstractLockRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/request/LockChangeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/request/LockChangeRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/request/ResourceLockChangeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/RepositoryTransactionContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/version/VersionCreateRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/version/VersioningConfiguration.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRepositoryCommitRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationJobRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
Labels: enhancement

#1219 feat(fhir): Add missing properties to CapabilityStatement
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/model/capabilitystatement/CapabilityStatement.java
  fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/model/capabilitystatement/Implementation.java
  fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/rest/tests/capabilitystatement/CapabilityStatementRestTest.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirMetadataController.java
Labels: enhancement

#1223 fix(core): Version the primary resource (potentially a collection...
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/version/VersionCreateRequest.java
Labels: bug
