Repository b2ihealthcare/snow-owl, pull requests merged in 2023-03, with the labels that each got.

#1119 Broken Promise response header propagation
  .github/workflows/maven.yml
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/AllSnowOwlApiTests.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/rate/RateLimitTest.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/util/PromiseMethodReturnValueHandler.java
  core/com.b2international.snowowl.core.tests/src/com/b2international/snowowl/core/events/util/PromiseTest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/events/util/Handler.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/events/util/Promise.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/events/util/Response.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/rate/ApiPlugin.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/rate/RateLimitingRequest.java
Labels: bug, enhancement

#1122 SO-5684: eliminate superfluous branch fetch request
  .github/workflows/maven.yml
  commons/com.b2international.index/src/com/b2international/index/revision/DefaultRevisionIndex.java
  commons/com.b2international.index/src/com/b2international/index/revision/DefaultRevisionSearcher.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranch.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionBranchRef.java
  commons/com.b2international.index/src/com/b2international/index/revision/RevisionSearcher.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemCompleteUpgradeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystemUpgradeSynchronizationRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/context/ResourceRepositoryCommitRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/context/TerminologyResourceContentRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/context/TerminologyResourceContentRequestBuilder.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/BranchContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/DelegatingBranchContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/RepositoryBranchContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/RepositoryContext.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/internal/ResourceRepository.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/locks/Locks.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BranchRealtimeContentRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BranchSnapshotContentRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/RevisionIndexReadRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/version/VersionCreateRequest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedPartialLoadingApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/BaseSnomedEclEvaluationRequestTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclShortcutTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedStatedEclEvaluationTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/validation/SnomedValidationIssueDetailTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/SnomedPlugin.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/SnomedRepositoryPreCommitHook.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRepositoryCommitRequestBuilder.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/Synonyms.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ExportRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/SnomedRf2ImportRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/exporter/Rf2Exporter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/exporter/Rf2LanguageRefSetExporter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/ConceptChangeConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/ConcreteDomainChangeConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/DescriptionChangeConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/converter/RelationshipChangeConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationCreateRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationJobRequest.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/snomed/TestBranchContext.java
  tests/com.b2international.snowowl.test.commons/src/com/b2international/snowowl/test/commons/validation/BaseValidationTest.java
Labels: enhancement

#1123 Introduce utility class to manage files with the NIO2 API
  commons/com.b2international.commons.test/src/com/b2international/commons/test/AllCommonsTests.java
  commons/com.b2international.commons.test/src/com/b2international/commons/test/io/PathUtilsTests.java
  commons/com.b2international.commons.test/src/com/b2international/commons/test/io/test_wo_folders.zip
  commons/com.b2international.commons/META-INF/MANIFEST.MF
  commons/com.b2international.commons/src/com/b2international/commons/FileUtils.java
  commons/com.b2international.commons/src/com/b2international/commons/io/PathUtils.java
Labels: carry-forward-8.x

#1124 SNRAY-1244: authorization performance improvements
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/authorization/AccessControl.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/authorization/AuthorizationService.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/authorization/AuthorizedRequest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/BaseResourceSearchRequest.java
Labels: enhancement

#1121 SO-5686: Skip existence check for non-SCT target components during ...
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/refset/SnomedReferenceSet.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedSimpleMapMemberCreateDelegate.java
Labels: carry-forward-8.x

#1130 Support `Accept-Language: "*"` headers
  commons/com.b2international.commons.test/.launch/commons-tests.launch
  commons/com.b2international.commons.test/META-INF/MANIFEST.MF
  commons/com.b2international.commons.test/src/com/b2international/commons/graph/LongTarjanTest.java
  commons/com.b2international.commons.test/src/com/b2international/commons/http/AcceptLanguageHeaderTest.java
  commons/com.b2international.commons.test/src/com/b2international/commons/test/AllCommonsTests.java
  commons/com.b2international.commons/src/com/b2international/commons/http/AcceptHeader.java
  commons/com.b2international.commons/src/com/b2international/commons/http/AcceptLanguageHeader.java
  commons/com.b2international.commons/src/com/b2international/commons/http/ExtendedLocale.java
  core/com.b2international.snowowl.core.rest.tests/src/com/b2international/snowowl/core/rest/codesystem/CodeSystemApiTest.java
  core/com.b2international.snowowl.core.rest/build.properties
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/codesystem/ExpressionLabelService.java
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/suggest/SuggestRestService.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ResourceRequestBuilder.java
  fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirCodeSystemController.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptSearchApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedClassificationRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedConceptRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedDescriptionRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedReferenceSetMemberRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedReferenceSetRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedRelationshipRestService.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedRf2ExportRestService.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequestBuilder.java
Labels: enhancement
