Repository b2ihealthcare/snow-owl, pull requests merged in 2024-05, with the labels that each got.

#1288 SO-6101: Classification error on SubAnnotationPropertyOf axioms
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/classification/SnomedClassificationApiTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/taxonomy/ReasonerTaxonomyBuilder.java
Labels: port-to-7.x

#1289 SO-6106: "Sub...PropertyOf" support for axiom-relationship conversions
  cis/com.b2international.snowowl.snomed.cis.product/.launch/snow-owl-cis.launch
  core/com.b2international.snowowl.core.rest.tests/.launch/core-e2e-tests.launch
  fhir/com.b2international.snowowl.fhir.rest.tests/.launch/fhir-api-tests.launch
  fhir/com.b2international.snowowl.fhir.rest.tests/.launch/fhir-unit-tests.launch
  fhir/com.b2international.snowowl.fhir.rest/.launch/fhir-api-server.launch
  pom.xml
  releng/com.b2international.snowowl.server.update/.launch/snow-owl-oss.launch
  snomed/com.b2international.snowowl.snomed.common/src/com/b2international/snowowl/snomed/common/SnomedConstants.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/.launch/snomed-e2e-tests (cis).launch
  snomed/com.b2international.snowowl.snomed.core.rest.tests/.launch/snomed-e2e-tests.launch
  snomed/com.b2international.snowowl.snomed.datastore.tests/.launch/snomed-core-unit-tests.launch
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/AllSnomedDatastoreTests.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/request/SnomedOWLExpressionConverterTest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/datastore/request/SnomedOWLRelationshipConverterTest.java
  snomed/com.b2international.snowowl.snomed.datastore/META-INF/MANIFEST.MF
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedOWLExpressionConverter.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedOWLRelationshipConverter.java
  snomed/com.b2international.snowowl.snomed.reasoner.tests/.launch/snomed-reasoner-unit-tests.launch
  snomed/com.b2international.snowowl.validation.snomed/.launch/validation-snomed-tests.launch
Labels: enhancement, port-to-9.x

#1293 SO-6120: change wild ECL evaluation to use wildcard query
  commons/com.b2international.index.tests/src/com/b2international/index/WildcardQueryTest.java
  commons/com.b2international.index/src/com/b2international/index/es/query/Es8QueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/es/query/EsQueryBuilder.java
  commons/com.b2international.index/src/com/b2international/index/query/Expressions.java
  commons/com.b2international.index/src/com/b2international/index/query/WildcardPredicate.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ecl/EclEvaluationRequest.java
  snomed/com.b2international.snowowl.snomed.datastore.tests/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequestPropertyFilterTest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequest.java
Labels: bug, enhancement

#1295 SO-6121: propagate namespaceConceptId when creating descriptions/relationships via concept create API
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/AllSnomedApiTests.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/components/SnomedConceptCreateApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/domain/SnomedConceptRestInput.java
Labels: bug

#1294 feat(snowowl.core): Small change required for downstream project
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/SnowOwl.java
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedCT_Release_INT_20150202_new_relationship_with_same_source_destination.zip
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/importer/Rf2RelationshipContentType.java
  snomed/com.b2international.snowowl.validation.snomed/META-INF/MANIFEST.MF
Labels: enhancement

#1296 SO-6100: remove unnecessary SHA1 conversion of jobId in RF2 import API
  snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/io/SnomedImportApiTest.java
  snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedRf2ImportRestService.java
Labels: bug

#1277 feat(snomed.reasoner): Reinstate equivalent concept merging extension
  core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/util/PromiseMethodReturnValueHandler.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/repository/ApiRequestHandler.java
  netty/com.b2international.snowowl.eventbus/src/com/b2international/snowowl/eventbus/IEventBus.java
  netty/com.b2international.snowowl.eventbus/src/com/b2international/snowowl/internal/eventbus/EventBus.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRefSetMemberSearchRequest.java
  snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRelationshipSearchRequest.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/SnomedReasonerPlugin.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/equivalence/IEquivalentConceptMerger.java
  snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
Labels: enhancement
