Repository b2ihealthcare/snow-owl, pull requests merged in 2025-07, with the labels that each got.

#1398 SO-6448: donated content reappears as added in revision compare results
  commons/com.b2international.index.tests/src/com/b2international/index/revision/RevisionCompareTest.java
  commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
Labels: bug

#1397 Introduce regular expression and wildcard TermFilter subclasses
  core/com.b2international.snowowl.core.tests/src/com/b2international/snowowl/core/AllCoreTests.java
  core/com.b2international.snowowl.core.tests/src/com/b2international/snowowl/core/request/search/TermFilterTest.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/search/RegexTermFilter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/search/TermFilter.java
  core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/search/WildcardTermFilter.java
Labels: feature

#1400 9.7.2 security updates
  commons/com.b2international.commons/.classpath
  commons/com.b2international.commons/META-INF/MANIFEST.MF
  commons/com.b2international.commons/pom.xml
  core/com.b2international.snowowl.core.rest/.classpath
  core/com.b2international.snowowl.core.rest/META-INF/MANIFEST.MF
  core/com.b2international.snowowl.core.rest/pom.xml
  core/com.b2international.snowowl.core.rest/snow-owl-api-docs/package-lock.json
  core/com.b2international.snowowl.core.rest/snow-owl-api-docs/package.json
  releng/target-platform/target-platform.target
Labels: security
